CREATE SEQUENCE teams_seq START WITH 5000 INCREMENT BY 1;
CREATE TABLE teams (
  id INT DEFAULT teams_seq.nextval PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  foundation_year INT NOT NULL,
  ranking_position INT NOT NULL,
  creation_date TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL);

CREATE SEQUENCE stadiums_seq START WITH 1000 INCREMENT BY 1;
CREATE TABLE stadiums (
  id INT DEFAULT stadiums_seq.nextval PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  capacity INT NOT NULL,
  city VARCHAR NOT NULL,
  team_id int NOT NULL UNIQUE,
  creation_date TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL);

CREATE SEQUENCE players_seq START WITH 7000 INCREMENT BY 1;
CREATE TABLE players (
  id INT DEFAULT players_seq.nextval PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  age INT NOT NULL,
  country VARCHAR NOT NULL,
  goals INT NOT NULL,
  team_id INT NOT NULL,
  creation_date TIMESTAMP AS CURRENT_TIMESTAMP NOT NULL);
